### ISSUE TITLE
Misleading reference to `config/isle-newsite-sample` in Migration Guide?

### ISSUE THREAD

**Issue by McFateM** [Islandora-Collaboration-Group/ISLE-Documentation#129]
I'm working back through the `04_installation_migration/migration_installation_guide/` and was confused by the last line listed below.  Specifically, I can't find ANY directory in any branch of ISLE named `config/isle-newsite-sample`.  All that exists is `config/proxy`, I believe. 

```
ON your local laptop / workstation:

    On the repository of your choice (GitHub, GitLab, Bitbucket, etc.) create a PRIVATE remote git repository - see the specific code repository documentation online for setup instructions.

    Open a terminal - navigate to /opt/ISLE or where you cloned the ISLE directory on your local workstation.

    Create a directory named yourdomain-config (where "yourdomain" is your server domain name)
        Example: digital-collections.yourdomain.com-config

    Within the ISLE directory, locate the directory called config/isle-newsite-sample and copy all the contents to the newly created directory
```

**Comment by bookishgirl** [comment]
Hi Mark,
I know. This documentation very much refers to ISLE 1.0 structure (which did have an isle-newsite-sample folder I believe). I am working on updating on the migration branch. if you want to - feel free to refer there and also to help edit!

**Comment by McFateM** [comment]
Thanks @bookishgirl, that explains a lot.  I would be happy to help, and I'll start by closing this issue since it's clearly part of a larger concern that you're addressing. 

I do have an additional suggestion and I'll toss that into a new issue so as not to confuse things any more than necessary.
