### ISSUE TITLE
Clarify Ansible working directory

### ISSUE THREAD

**Issue by ctgraham** [Islandora-Collaboration-Group/ISLE-Documentation#2]
Porting from https://github.com/Islandora-Collaboration-Group/ISLE/issues/107

We say `cd /path/to/ISLE/repo` before running the ansible test, but we really mean something like `cd /path/to/ISLE/repo/ansible/`.

See, for example:
https://github.com/Islandora-Collaboration-Group/ISLE-Documentation/blame/c9f6655bfadef219c76fe4292bfe734ad7dddf96/docs/00Host_Server/Host_Server_Setup_Ansible.md#L242

**Comment by g7morris** [comment]
Thanks @ctgraham for pointing this out. Have now fixed this with this [commit](https://github.com/Islandora-Collaboration-Group/ISLE-Documentation/commit/b0c5f59800a2ff772c3f7061823f119615f5295f)
