### ISSUE TITLE
Detailed instructions for host software

### ISSUE THREAD

**Issue by marksandford** [Islandora-Collaboration-Group/ISLE-Documentation#40]
Right now we are including step by step instructions for installing things like Vagrant and Virtualbox.  Should we instead list any specific requirements (like VBox Extensions) that need to be installed/configured and point users to the official docs?  As OSes change, our docs will become out of date sooner if we are describing a click-by-click process on straightforward installation of software.

**Comment by bookishgirl** [comment]
that makes a lot of sense to me.

**Comment by dwk2** [comment]
I am in agreement with Mark, too. 

I think it's important that special care is taken in ensuring smooth transitions between instructions to use third-party external_official_docs and then returning to the ISLE install process. The smoother those transitions are, the fewer people we'll lose.

**Comment by bookishgirl** [comment]
Like - have links pop-out to a new page and include a note in our instruction both that this is happening and as a reminder to return back to continue ISLE process once they have completed steps at the other site?

**Comment by marksandford** [comment]
Just FYI:  Github's pages don't allow for links to open in a new tab, so users will have to take it upon themselves to sort that out via middle click, ctrl+click, etc.  I'm assuming anyone tackling a test installation will have basic browser skills, though (a lot to expect, I know!).

**Comment by marksandford** [comment]
Done, or as done as possible for now.
