### ISSUE TITLE
Mac Vagrant & VirtualBox

### ISSUE THREAD

**Issue by marksandford** [Islandora-Collaboration-Group/ISLE-Documentation#57]
Is there a compelling reason to support Vagrant & Virtualbox rather than just Docker, since Docker is so much easier?

**Comment by br2490** [comment]
The only reason I use a VM in my work is for rapid development and testing.  For the average user: no!  You're accurate when you say docker and docker-compose is meant to do the heavy lifting; and if I'm able to learn Ansible that will auto-provision a server using the aforementioned tools and dependencies. 

Advise deprecation. (Development and testing on a VM (Vagrant) requires a decently powerful VM, or at least it should - just nope.)

**Comment by marksandford** [comment]
Per conversation, some concern that ISLE alphas, other early adopters, may be familiar and comfortable in Vagrant.  Doc will remain for now, but marked as deprecated and Docker noted as preferred for most users.
