### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by marksandford** [Islandora-Collaboration-Group/ISLE-Documentation#71]
Documentation for Let's Encrypt (https://docs.traefik.io/user-guide/docker-and-lets-encrypt/).  Probably more relevant to migration.  Will need to qualify any tests with note that not all users will want to/be able to go down this route.

**Comment by g7morris** [comment]
@marksandford ^ THIS!!! I've attempted to test this route and have had no positive results. We need to figure out why this fails in ISLE 1.1 currently. @marksandford @br2490

**Comment by marksandford** [comment]
Has this been sorted out in terms of failing in 1.1?  If so, we'll need to write up docs for implementing.
