### ISSUE TITLE
Broken link on ISLE DOCS homepage

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE-Documentation#80]
Broken link from "Test/Demo ISLE" link at top of page to the corresponding section at bottom of page.
https://islandora-collaboration-group.github.io/ISLE-Documentation/#test-demo-isle

How do I create a link on same page, or is that a function of mkdocs? (And if the latter, how do I do that?)

**Comment by marksandford** [comment]
I fixed it.  The link should have been #testdemo-isle rather than #test-demo-isle.   Presumably mkdocs generates header IDs by stripping the / rather than inserting a hyphen.  In order to get the io docs to reflect the change, mkdocs is necessary (I did that, too, no worries).

**Comment by dwk2** [comment]
Thank you Mark! Issue fixed. Closing issue.
